### ISSUE TITLE
i18n new strings, see e.g. ron-full

### ISSUE THREAD

**Issue by killerducky** [killerducky/killer_mortal_gui#14]
https://github.com/killerducky/killer_mortal_gui/commit/59c7eed26acc493f5461719964ba6bb2d047154b
@cjeon @sabertazimi 

Added a few more strings, and tried to translate them myself. Should Korean ron-full be {{loser}}에서?

"ron-full"  : "{{winner}}의 론 {{loser}}",

Some of the new strings are only used in a new feature that I'm still working on. You can take a look by opening dev console and running:
`MM.GS.alphaTestMode=true`

Then go to the end of a round where someone called Riichi, and hit `d`

There are still many strings in this that I didn't add to translate yet, and it's all probably going to change a lot so don't bother doing anything with those yet.

**Comment by sabertaz** [comment]
Chinese version looks nice.
