### ISSUE TITLE
Extra keyboard shortcut for prev mistake and next mistake for convinience?

### ISSUE THREAD

**Issue by cjeon** [killerducky/killer_mortal_gui#16]
Currently mistake navigation shortcut keys are page up and page down as below

``` js
        } else if (event.key == 'PageUp') {
            do {
                decPlyCounter();
            } while (!stopCondition(true))
            updateState()
        } else if (event.key == 'PageDown') {
            do {
                incPlyCounter();
            } while (!stopCondition(true))
            updateState()
        }
```

My main machine does not have page up or page down key (mac book pro) so I have to click manually. 

Something like `[` for prev and `]` for next could work, I think. If you agree, I can open PR myself for the change 👍

**Comment by killerducky** [comment]
How about this. I used ,. for pgup/pgdn, and [] for home/end
https://github.com/killerducky/killer_mortal_gui/commit/8a2b43c451ee65723733a65c6dc6276c0696c847
