### ISSUE TITLE
Shortcut info on the about modal

### ISSUE THREAD

**Issue by cjeon** [killerducky/killer_mortal_gui#17]
Many people might not know the existence of the shortcuts (maybe arrow keys, but doubt others).

I think adding some descriptions for the shortcuts in the about modal will improve usability.  

If you agree I can open the PR myself.

**Comment by killerducky** [comment]
https://github.com/killerducky/killer_mortal_gui/commit/bdcb3c5d2973dd79a7a5087601c9fd72cb1625e8

**Comment by killerducky** [comment]
Was planning to do this sometime, so here it is!
