### ISSUE TITLE
Occasional misplacement of cards

### ISSUE THREAD

**Issue by Dilaen** [killerducky/killer_mortal_gui#2]
When I was using [Mortal](https://mjai.ekyu.moe/) to review my game as usual, I surprisingly found that the GUI changed to this new "KillerDucky" style! First, I must thank you for your work on making Mortal's GUI more interesting (or "NAGA-like" if I may say). I couldn't wait to try this new GUI and seemed to find a minor bug——in some cases, a card might appear in a wrong position. Let me illustrate it with the pictures below.

1. Here I chose to "chi" the 6p from my left player using 4p0p, which is different from Mortal's choice.

<img width="717" alt="微信图片_20240302001642" src="https://github.com/killerducky/killer_mortal_gui/assets/61322546/a66e1448-696e-4687-8184-c8671ffb8a5a">

2. After I clicked "Next" button, the 6p in my hand suddenly jumped to the rightmost position. However, it was supposed to stay on the right of and next to 5p!

<img width="718" alt="微信图片_20240302001721-2" src="https://github.com/killerducky/killer_mortal_gui/assets/61322546/c10bb0ac-e8c6-44aa-b6b2-94aa9b0e1413">

3. After I cut "haku" next turn, the 6p in my hand jumped back to where it was supposed to be and stayed in the correct position till the end of this round.

<img width="717" alt="微信图片_20240302002316" src="https://github.com/killerducky/killer_mortal_gui/assets/61322546/3c37549c-8817-430f-8150-5c6d9d7b5702">

By the way, the problem described above doesn't appear on the replay viewer of "Classic" UI.

**Comment by killerducky** [comment]
Thanks for your report. I noticed it too and have a fix locally, it will be fixed in the next release.

**Comment by killerducky** [comment]
Fixed by https://github.com/killerducky/killer_mortal_gui/commit/86889d508e59fe450c92424ffef7505d5bdb9940
Not released yet.
