### ISSUE TITLE
Mortal Evaluation Data Dump

### ISSUE THREAD

**Issue by baronvonfonz** [killerducky/killer_mortal_gui#25]
If there is already a way to view this data in the UI without debugging JS, please let me know. 

I think it would be very useful if for a given choice in addition to rendering green and yellow bars, the evaluation data could be dumped into a modal with some light/basic formatting. 

Specifically, in instances like this eyeballing the relative confidence bars makes me want to see more detail into the comparison between the two decisions in the `GS.ge` matrix.

![image](https://github.com/killerducky/killer_mortal_gui/assets/123319797/012f38e8-9e10-4d8b-8250-769e22d60d61)

**Comment by Sucaiking** [comment]
在模拟牌桌的界面中，有足够的空间以及方法显示每一打的区别了。
当用户的鼠标移动到某一操作上方时（比如移动到riichi上时），可以增加悬浮窗，显示出听牌情况；如果比较的是切牌的优劣，可以显示牌理。

**Comment by killerducky** [comment]
Table added.
