### ISSUE TITLE
Some questions about rating

### ISSUE THREAD

**Issue by haoyun0** [killerducky/killer_mortal_gui#27]
In fact, there are many instances in games now where AI cheating is being used. And many people now rely on this rating option to judge whether players are using AI cheating.

However, those who cheat using AI are quite cunning. Sometimes, they deliberately minimize the "AI consistency" when there's little difference in the choices made in the first and second positions. But I believe the primary indicator should be the rating, because even with the aforementioned method to reduce consistency, the rating will still be very high.

In the explanation of the rating, you mentioned that the rating is meaningless, and some people who cheat using AI argue that having a high rating is pointless. But my viewpoint is that the rating is the most reflective indicator of similarity to this mortal model. Am I correct in my understanding?

If so, could relevant explanations be added to the rating description? Not just stating that the rating is directly related to the model, but proposing how it is related. For instance, a higher rating indicates a closer alignment with the model's thought process. I'm a bit confused right now because several individuals who cheat using AI are arguing with me, saying that the rating is completely useless.

**Comment by cloudfish** [comment]
The author of Killer Mortal GUI is not the author of Mortal.
https://github.com/Equim-chan/Mortal/discussions may be a more suitable place for this.
