### ISSUE TITLE
[Feature Request] Missing i18n suuport

### ISSUE THREAD

**Issue by sabertazimi** [killerducky/killer_mortal_gui#8]
- [x] 1. `E`, `S`, `W`, `N`.
- [x] 2. Spoiler-free words in `.discard-bars`: `Spoiler: Mortal evaluations hidden. Click to show`.
- [x] 3. Advice words in `.killer-call-bars`: `Cut`, `Pass`, `Chi`, `Pon`, `Kan`, `Riichi`, `Clack!`, `Hmm...`.
- [x] 4. Keys and values in `.about-metadata` table.
- [x] 5. Webpage title: `Killer Mortal Reviewer`.
- [x] 6. Points words in `.info-this-round-modal`: `Fu`, `Han`, `Points`, `Each`, mangan+ point names, Yaku names.
- [x] 7. Missing translation for value of game length in metadata table: `Hanchan` -> `半庄`.

**Comment by killerducky** [comment]
I think everything should be ready for translation except the Points/Yaku stuff.

**Comment by sabertaz** [comment]
Missing translation for value of game length in metadata table: `Hanchan` -> `半庄`.

**Comment by killerducky** [comment]
I think everything should at least have a key now.

**Comment by sabertaz** [comment]
Awesome job!
